[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.2"
tag_format = "$version"
update_changelog_on_bump = true
bump_message = "release: $current_version â†’ $new_version"
version_files = ["src/main.rs:version", "Cargo.toml:^version"]